[[ -z "${TERM}" ]] && export TERM=xterm

alias l='ls -lh'
alias la='ls -lha'

BASH_PROFILE=`readlink -f ${BASH_SOURCE}`
REAL_HOME=`dirname "${BASH_PROFILE}"`
export REDSHELL_ROOT="${REAL_HOME}/.redshell"
export EDITOR=`which vim`

if [[ `uname -a` == *debian* ]]
then
    PATH=/usr/sbin:/sbin:$PATH
fi

export HISTCONTROL=ignoredups:erasedups
export HISTSIZE=100000
export SAVEHIST=100000
# This is necessary on macOS, otherwise they overwrite HISTFILE with something
# weird.
shopt -s histappend

VISUAL="$(cat ${REAL_HOME}/.redshell_visual | tr -d '\n')"

pushd "${REAL_HOME}/.redshell/src" > /dev/null
for f in ./*.bash; do
    source $f
done
popd > /dev/null

__prompt_color() {
    case "$1" in
        bmo)
            echo -ne '\033[38;5;36m'
        ;;
        lighthouse)
            echo -ne '\033[38;5;196m'
        ;;
        astronaut)
            echo -ne '\033[38;5;205m'
        ;;
        pacman)
            echo -ne '\033[38;5;226m\033[48;5;16m'
        ;;
        dachshund)
            echo -ne '\033[38;5;215m'
        ;;
        saturn)
            echo -ne '\033[38;5;76m'
        ;;
        drwho)
            echo -ne '\033[38;5;32m'
        ;;
        snufkin)
            echo -ne '\033[38;5;106m'
        ;;
        moose)
            echo -ne '\033[38;5;94m'
        ;;
        bessy)
            echo -ne '\033[48;5;160m\033[38;5;15m'
        ;;
    esac
}

__prompt_escape() {
    echo -n "\[\033[1m\]"
    [[ -z "$VISUAL" ]] || echo -e "\[$(__prompt_color $VISUAL)\]"
}

__git_info() {
    git rev-parse --is-inside-work-tree 2> /dev/null > /dev/null
    ret=$?
    if [[ $ret -eq 0 ]]; then
        c=$(git status -s | wc -l | tr -d ' ')
        b=$(git branch --show-current | tr -d '* \n')
        h=`git rev-parse --short HEAD`
        echo -n "(git ${b}:${h}"
        if [[ "$c" -ne "0" ]]; then
            echo -n "+${c}"
        fi
        echo -n ") "
        return
    fi
}

__hg_info() {
    hg_ps1_widget || true
}

__error_info() {
    ret=$?
    case "$ret" in
        "0")
        ;;
        "126")
            echo -n "(EPERM [${ret}]) "
        ;;
        "127")
            echo -n "(ENOENT [${ret}]) "
        ;;
        "130")
            echo -n "(EINT [${ret}]) "
        ;;
        *)
            echo -n "(E [${ret}]) "
        ;;
    esac
}

__screen_info() {
    if [[ "$STY" != "" ]]; then
        echo "(s:${WINDOW}) "
    fi
}

__addr() {
    ips="`net_ip4`" || return 1
    n=`wc -l <<< "$ips"`
    if [[ n -eq 1 ]]; then
        echo "${ips}"
    else
        first=`head -n1 <<< "$ips"`
        k=`bc -l <<< "$n - 1"`
        echo "${first} + $k"
    fi
}

__addr_info() {
    a=`__addr` || return 1
    echo "(${a}) "
}

__time_info() {
    t=`date +%T` || return 1
    echo "(${t}) "
}

PS1_PREFIX="┌─|\[\033[0m\]\u@$(__prompt_escape)\h\[\033[0m\] \w "
PS1_WIDGETS="\[\033[38;5;196m\]\$(__error_info)" # Has to be first
PS1_WIDGETS+="\[\033[32m\]\$(__time_info)"
PS1_WIDGETS+="\[\033[38;5;26m\]\$(__git_info)"
PS1_WIDGETS+="\[\033[38;5;26m\]\$(__hg_info)"
PS1_WIDGETS+="\[\033[38;5;33m\]\$(__screen_info)"
PS1_WIDGETS+="\[\033[38;5;214m\]\$(__addr_info)"
PS1_SUFFIX="\[\033[0m\]\n└─> "

PS1="${PS1_PREFIX}${PS1_WIDGETS}${PS1_SUFFIX}"


vid() {
    [[ -z "$VISUAL" ]] || "${REAL_HOME}/.redshell/asciiart/${VISUAL}.sh"
}

status() {
    vid
    echo "Local time: `date`"
    echo "This node: `hostname` (`uname -srm`)"
    uptime
    
    local wifi=`net_wifi_name 2> /dev/null`
    [[ -z "${wifi}" ]] || echo "Connected to ${wifi}"
    return 0
}

export PATH=$HOME/bin:$PATH

# Mainly Claude uses this, but also others.
export PATH=$HOME/.local/bin:$PATH

if [[ $- != *i* ]]; then
    export REDSHELL_SILENT=1
fi

[[ -z "${REDSHELL_SILENT}" ]] && status || true

 [[ -r "/opt/homebrew/etc/profile.d/bash_completion.sh" ]] && . "/opt/homebrew/etc/profile.d/bash_completion.sh"

if [[ `uname -a` == *Darwin* && $- == *i* ]]
then
    # bind 'TAB:menu-complete'
    # bind '"\e[Z":menu-complete-backward'
    bind 'set colored-completion-prefix on'
    bind 'set show-all-if-ambiguous on'
fi
