# Debian and macOS are both completely stupid about locales. macOS sets locales
# that don't exist and no amount of brute force seems to stop it. Debian
# completely implodes as soon as anything is the least bit off.
#
# I have no patience for this stupidity. Just always set this locale and leave
# me alone.
export LC_ALL=en_US.UTF-8
unset LC_CTYPE

# Use emacs keybindings (CTRL+R, CTRL+A, etc.) regardless of $EDITOR.
bindkey -e
bindkey "^[[3~" delete-char # Delete key

# Load zsh completion system
autoload -Uz compinit
compinit -u 2>/dev/null

# Load zsh-generated completion for q, if available
if [[ -f "${HOME}/.redshell/src/quick.gen.zsh" ]]; then
    source "${HOME}/.redshell/src/quick.gen.zsh"
fi
