#compdef q
# Generated by quick.py. Do not edit.
# Run q quick rebuild to regenerate.

_q() {
    local -a modules functions

    if (( CURRENT == 2 )); then
        modules=(
            'ai:AI tools setup and configuration.'
            'ascii_art:Assorted ascii art, screen drawing and speech bubbles.'
            'bash:Parse bash files and automate bash scripting.'
            'browser:Browser automation, downloads, link generators.'
            'caldav:CalDAV calendar fetching utilities.'
            'crypt:Encrypt/decrypt, signing, keypairs. SSH and GPG helpers.'
            'debian:Debian setup and package management.'
            'file:File helpers.'
            'find:Shorthands for find and grep.'
            'git:Automate git and github operations.'
            'go:Helpers for dealing with Go packages.'
            'hg:Mercurial helpers.'
            'install:Install a file into another file, optionally with a keyword.'
            'kagi:Kagi search and API wrappers.'
            'keys:Key management utils using pass and gpg.'
            'mac:Mac setup, package management and various helpers.'
            'media:Functions for working with media, ffmpeg, youtube, etc.'
            'monitor:System load monitoring and logging.'
            'mtg:Stuff for Magic: The Gathering.'
            'multiple_choice:Interactive multiple choice prompts.'
            'net:Network and wifi helpers, netcat wrappers, etc.'
            'news:News and weather.'
            'notes:Note management based on git and markdown.'
            'omdb:OMDB (Open Movie Database) helpers for bash.'
            'path:UNIX style path helpers.'
            'pkg:Cross-platform package management.'
            'python:Python env management, python-shell FFI and Jupyter.'
            'quick:Redshell function help, switch and autocomplete.'
            'redhat:Red Hat family (RHEL, Fedora, Rocky, Alma, CentOS) setup and package management.'
            'rust:Manage rust toolchain and environment.'
            'screen:UNIX style path helpers.'
            'strings:String helpers for bash and zsh.'
            'time:Time and date helpers.'
            'transit:Transit helpers.'
            'util:Catch-all utility functions that don'\''t fit anywhere else.'
            'xterm_colors:Work with the xterm color space, convert to RGB, etc.'
        )
        _describe 'module' modules
        return
    fi

    if (( CURRENT == 3 )); then
        case "${words[2]}" in
        ai)
            functions=(
                'install_claude_config:Installs Claude Code configuration files from redshell.'
            )
            _describe 'function' functions
            ;;
        ascii_art)
            functions=(
                'print_speech_bubble:'
                'erase_lines:'
                'cursor_position:'
                'cursor_row:'
                'astronaut:'
                'bessy:'
                'bmo:'
                'dachshund:'
                'drwho:'
                'lighthouse:'
                'moose:'
                'pacman:'
                'saturn:'
                'snufkin:'
                'pedro:Print the pedro raccoon with random contrasting colors.'
                'print_pedro:'
                'scroll_output_pedro:'
                'select_visual:'
            )
            _describe 'function' functions
            ;;
        bash)
            functions=(
                'get_bash_functions:'
            )
            _describe 'function' functions
            ;;
        browser)
            functions=(
                'gdocs_id:Extracts a Google Docs ID from a URL.'
                'sheets_dl_link:Usage sheets_dl_link URL [FORMAT]'
                'chrome_path:Returns the path to the Chrome executable.'
                'downloads_path:Returns the path to the Downloads folder.'
                'dl:Downloads a URL with the browser and returns the path to the downloaded file.'
            )
            _describe 'function' functions
            ;;
        caldav)
            functions=(
                'accounts:List configured CalDAV accounts.'
                'fetch:Fetch a CalDAV calendar and output its contents.'
                'agenda:Show upcoming events from a CalDAV calendar.'
            )
            _describe 'function' functions
            ;;
        crypt)
            functions=(
                'encrypt_symmetric:'
                'decrypt_symmetric:'
                'gen_github_keypair:'
                'package:'
                'payloadify:'
                'downloadify:Encrypt a file and wrap it in a base64 self-unpacking shell script.'
                'hash:Print a cryptographic hash of the input.'
                'selfsign:Generate a self-signed certificate.'
            )
            _describe 'function' functions
            ;;
        debian)
            functions=(
                'setup:'
                'install_extras:Install the full development environment on Debian/Ubuntu.'
                'install_or_skip:'
                'install_imgcat:'
                'setup_mc:'
            )
            _describe 'function' functions
            ;;
        file)
            functions=(
                'mktemp:Cross-platform version of mktemp across BSD and GNU. Creates a temp file and'
                'mtime:Returns the modification time of PATH in "YYYY-MM-DD HH:MM:SS" format.'
                'age:'
            )
            _describe 'function' functions
            ;;
        find)
            functions=(
                'f:Shorthand for find'
                'fcc:'
                'fgo:'
                'fjava:'
                'faidl:'
                'fd:'
                'replace:Usage find_replace [DIR] GLOB NEEDLE REPLACEMENT'
            )
            _describe 'function' functions
            ;;
        git)
            functions=(
                'mkproject:'
                'ssh_init:'
                'get_origin:'
                'master_branch:'
                'cherrypick_branch:'
                'sparse_clone:Clones a git repository with only the specified subdirectories.'
                'changed_lines:'
            )
            _describe 'function' functions
            ;;
        go)
            functions=(
                'pkg_do:'
            )
            _describe 'function' functions
            ;;
        hg)
            functions=(
                'root:Fast check for mercurial. (About 100 times faster than `hg root`.) Prints the'
                'repo_name:'
                'branch_name:'
                'ps1_widget:'
            )
            _describe 'function' functions
            ;;
        install)
            functions=(
                'file:Installs the contents of DFILE into SFILE, guarded by a comment at the first'
                'reinstall_file:This is a legacy form of install_file. It is kept for backwards compatibility.'
            )
            _describe 'function' functions
            ;;
        kagi)
            functions=(
                'search_json:'
                'summarize_json:'
            )
            _describe 'function' functions
            ;;
        keys)
            functions=(
                'git:Wraps git for use with the keys repository.'
                'path:Dumps the contents of the given key in a file and returns the path.'
                'var:Returns the conents of a given .var key in pass. If VALUE is provided, instead'
                'key:Returns the contents of a given .key key in pass. If VALUE is provided,'
                'flush:Removes all cached key files.'
                'sync:Pulls the latest changes from the keys git repository and pushes any local'
            )
            _describe 'function' functions
            ;;
        mac)
            functions=(
                'setup:'
                'install_extras:Install the full development environment on macOS. This includes switching to'
                'brew:'
                'reinstall_brew:'
                'enable_ipconfig_verbose:'
                'get_user_shell:'
                'brew_bash_path:'
                'switch_to_bash:'
                'icloud:'
                'icloud_evict:'
                'brew_install_or_skip:'
                'install_miniconda:'
                'install_devtools:'
                'kill_defender:Kills Microsoft Defender in a way that tends to persist for an hour or so.'
                'suppress_defender:Keeps Microsoft Defender from restarting.'
                'kill_crashplan:Stops CrashPlan from running. CrashPlan is a very poorly optimized backup'
                'hogs:'
                'cpu_hogs:Lists PIDs of processes using too much CPU.'
                'cpulimit:Limits the CPU usage of processes to a certain percentage.'
                'disable_powernap:Stop the computer from waking up to do random things and exhausting the'
                'power_stats:Prints out some debug information about power management.'
                'fix_ssh_locale_config:macOS uses the non-existent locale LC_CTYPE=UTF-8 by default, which breaks SSH'
                'pid_suspend:'
                'setup_iterm2:'
            )
            _describe 'function' functions
            ;;
        media)
            functions=(
                'yt-dl:Wrapper areound yt-dlp. Automatically ensures dependencies are installed.'
            )
            _describe 'function' functions
            ;;
        monitor)
            functions=(
                'stream_load_stats:'
                'load_hist:'
                'latest_load_stats:'
                'write_load_stats:'
                'stream_top_stats:'
                'stream_net_stats:'
                'proc_stats:Outputs:'
            )
            _describe 'function' functions
            ;;
        mtg)
            functions=(
                'oracle_json:Fetch the latest oracle cards from Scryfall and return the path to the JSON'
                'rules:'
                'card_json:Return the JSON object for the card with the given name. (Case sensitive.)'
                'card:Print the Magic: The Gathering card with the given name. (Case sensitive.)'
            )
            _describe 'function' functions
            ;;
        multiple_choice)
            functions=(
                'multiple_choice:Display an interactive menu with multiple choices, and then print the selected option to stdout.'
            )
            _describe 'function' functions
            ;;
        net)
            functions=(
                'host:Hosts a folder contents over HTTPs.'
                'dl:Recursively downloads the URL even if it'\''s a folder. Accepts all wget options.'
                'online:Check if you have a usable internet connection.'
                'cidr_to_netmask:Convert a CIDR notation (e.g. 24) to a netmask.'
                'health:'
                'ssh_fingerprint:'
                'dump_cert:'
                'ccurl:Cached curl wrapper. Request parameters are converted to a key and used to'
                'dataurl:Create a data URL from a file.'
                'undataurl:Decode a dataurl from stdin onto stdout.'
                'rtt:Average round-trip time to the specified host.'
                'ip4:Print the non-localhost IPv4 addresses of this machine. One address per line.'
                'ip4gw:Print the default gateway'\''s IP address.'
                'port_hog:Find the process using a TCP port.'
                'serve:Serves the contents of a file or stdin over HTTP once, then exits.'
                'dump_url:'
                'wiki:'
                'wifi_device:'
                'wifi_name:Print the name of the currently connected wifi network.'
                'ssh_fingerprint:'
                'ssh_aliases:Prints the aliases and hostnames from the ssh config file.'
                'ssh_fqdn:Based on SSH config, looks up the full hostname of the given alias.'
                'wa_link:Prints a link to WhatsApp Web for the given phone number.'
                'gallery:Scan a directory for photos and serve a browsable gallery.'
            )
            _describe 'function' functions
            ;;
        news)
            functions=(
                'all:'
                'stocks:'
                'weather:'
                'brutalist_report_source:'
                'nytimes:'
                'npr:'
                'pbs:'
                'register:'
                'cnbc:'
            )
            _describe 'function' functions
            ;;
        notes)
            functions=(
                'note:Saves the provided note, intelligently placing it and generating a title. If'
                'list:'
                'sync:'
                'todo:Shows an interactive listing of matching TODOs.'
                'undo:Undoes the last note change. If the last change was to a local note, it will'
                'perl:Applies the provided perl program to matching notes to generate replacements.'
                'api_list_notes:Outputs a list of notes files that match the given terms.'
                'backup:Backs up the notes repository to a timestamped tarball in the notes root.'
                'api_empty_notes:Lists empty notes.'
                'api_list_todos:Lists TODOs matching the given context and terms.'
                'print_todo_categories:'
                'api_git:Forwards its args to git running with the correct key and in the notes root.'
                'api_pushd:'
                'api_clone:Clones the git reposity.'
                'api_fsck:Resets the mtime of notes files from git.'
                'nw:'
                'window:'
                'api_find:Runs find automatically scoped to the right mtime by the NEND and NSTART env'
                'api_quick_title:'
                'log:'
                'api_match_files:Returns a list of files, as absolute paths, that match a search query. The'
                'ls:Prints a tree of notes, with the TERM as a filter.'
                'hist:Prints the N most recent notes.'
                'api_drop_note:Delete the note at the provided relative path.'
                'gc:Deletes empty notes and runs git gc.'
                'api_update_note:Updates the note at the given relative path with the given contents.'
                'api_edit_note:Opens vim for the given relative note path, then updates the notes tree using'
                'api_perl_preview:Applies the provided perl program to matching notes to generate replacements.'
                'claude:Opens a Claude Code session in the notes repository.'
                'api_pushd:Changes to the notes repository directory. (With pushd.)'
            )
            _describe 'function' functions
            ;;
        omdb)
            functions=(
                'set_key:Configure a new KEY for the OMDB API.'
                'register_key:Interactive prompt to configure the API key for OMDB.'
                'get_key:Prints the API key for OMDB.'
                'query:Query the OMDB API with the given query. Prints JSON to stdout. Results are'
                'guess_title:Guess the title of the movie based on the filename.'
            )
            _describe 'function' functions
            ;;
        path)
            functions=(
                'expand:Expands tilde, safely, in the path.'
                'resolve:Prints the absolute path of PATH, with any tilde interpolated.'
                'push:This is like pushd, except it also updates the name of the screen window to'
                'pop:This is like popd, except it also updates the name of the screen window to the'
            )
            _describe 'function' functions
            ;;
        pkg)
            functions=(
                'install_or_skip:Install packages using the system package manager, or skip, if the package is'
            )
            _describe 'function' functions
            ;;
        python)
            functions=(
                'venv:Create a new virtualenv in the current directory, using the latest available'
                'pip_run:Run a Python script with the specified package installed.'
                'ipynb:Creates a new virtualenv in the current directory (as venv) and opens a new'
                'detect:Find all available Python binaries in the PATH and their versions.'
                'latest:Returns the path to the latest available Python binary.'
                'func:Run a Python function from a file. Calls `q python venv` to setup the'
                'black:Run the black code formatter on the specified files.'
            )
            _describe 'function' functions
            ;;
        quick)
            functions=(
                'rebuild:'
                'q:'
            )
            _describe 'function' functions
            ;;
        redhat)
            functions=(
                'setup:'
                'install_extras:Install the full development environment on RHEL/Fedora/Rocky/Alma/CentOS.'
                'dnf_install_or_skip:Install a package with dnf if it'\''s not already installed.'
                'install_imgcat:'
                'setup_mc:'
            )
            _describe 'function' functions
            ;;
        rust)
            functions=(
                'rustup:'
                'install_goodies:'
            )
            _describe 'function' functions
            ;;
        screen)
            functions=(
                'session:'
                'window:'
                'rename:'
                'home:'
                'reset_dirname:'
            )
            _describe 'function' functions
            ;;
        strings)
            functions=(
                'urlencode:Usage strings_urlencode STRING'
                'strip_control:Strips terminal escape sequences from standard input.'
                'repeat:Prints STRING N times.'
                'join:'
                'sgrep:'
                'strip_prefix:Strips the prefix from the string if it'\''s there.'
                'trim:Strips leading and trailing whitespace from a string.'
                'elide:Elides TEXT to LIMIT characters, inserting "(...)" in the middle if needed.'
                'strip_prefix:Strips the prefix from the string if it'\''s there.'
            )
            _describe 'function' functions
            ;;
        time)
            functions=(
                'zones:List all time zones know to the system. (In /usr/share/zoneinfo.)'
                'get_tz:'
                'local:'
                'utc:'
                'in:Usage time_in TIMEZONE [FORMAT]'
                'tz_diff:'
                'ts:'
                'convert:'
            )
            _describe 'function' functions
            ;;
        transit)
            functions=(
                'sbb:'
            )
            _describe 'function' functions
            ;;
        util)
            functions=(
                'ddu:'
                'sudo:'
                'reload:'
                'markdown:'
                'human_size:Convert SIZE to human-readable format.'
                'install_heroku_cli:'
                'install_bazelisk:'
                'jup:'
                'wait_for_file:'
                'forex:'
                'run:'
            )
            _describe 'function' functions
            ;;
        xterm_colors)
            functions=(
                'channel_step:Takes one RGB channel value as a 2-byte hex string and returns a decimal'
                'greyscale_step:As channel_step, but for greyscale.'
                'rgb_to_xterm:Takes an RGB color as a 6-byte hex string and returns the closest xterm color.'
                'hue_diff:Computes the hue difference between two RGB colors passed as 6-byte hex'
                'brightness:Computes the brightness of an RGB color passed as a 6-byte hex string. Result'
                'contrast:Computes a contrast value between two RGB colors passed as 6-byte hex strings.'
                'xterm_to_rgb:Takes an xterm color number as a decimal integer and returns a 6-byte hex of'
                'xterm_to_fg:'
                'xterm_to_bg:'
                'tfmt:'
                'color:'
                'shades:'
                'colors:'
            )
            _describe 'function' functions
            ;;
        esac
        return
    fi

    # For remaining arguments, fall back to file completion
    _files
}

compdef _q q
